### PR TITLE
Updated README for new workflow

### PR DESCRIPTION
**Pull request by atjonathan**
Refer #188

### CODE REVIEW

**Comment by atjonathan** [comment]
Remember to squash :+1: :shipit:

**Comment by brianamarie** [comment]
@atjonathan  Ah yes, squashing is definitely not a part of my typical workflow, and I will need reminding! 👍 

This looks fantastic! Remind me of the typical Free Code Camp workflow here...do you merge your own PR after someone else puts 👀  on it, or does someone else merge it?

**Comment by atjonathan** [comment]
@brianamarie, someone else merges. When you click the `Merge pull request` button, use the dropdown, to choose the squash option. If this looks good, feel free to merge, thanks!

**Comment by brianamarie** [comment]
@atjonathan Thank you for all of your ✨  work on this! 

img

**Pull request merged**
