### PR TITLE
Created ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by atjonathan**
[WIP] Please `squash` on merge :+1: 
What else needs added @brianamarie?

Refer #188

### CODE REVIEW

**Comment by brianamarie** [comment]
@atjonathan Awesome! Thanks again for your help on this.

I have a question...will contributors need a certain access to be able to add labels? It was my understanding that users needed collaborator access to be able to do that. 

 I'd add these myself but can't because it's on your branch - thoughts? 

----
`<If you are creating this issue to help make a video (or videos!), please use this template to track your progress. If you are creating an issue for another purpose, like to suggest a topic, notify us of a bug or inaccuracy, or help organize this repository, you can delete this template. Thank you for contributing! >`

### VIDEO-CHALLENGE-NAME Tracking Issue
This checklist will lead you through the steps of contributing to video challenges! Anywhere along the way, reach out for help by typing `@brianamarie I need help!` in a comment, by asking for help in the [Video Challenge Chat on Gitter](https://gitter.im/FreeCodeCamp/hikes), or in the [Help Contributors Chat on Gitter](https://gitter.im/FreeCodeCamp/HelpContributors).

#### 1. Get Ready
- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)

#### 2. Write your Script 
- [ ] [Fork this repository](https://help.github.com/articles/fork-a-repo/) to your personal account 
- [ ] [Create a new branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) with `<yourusername-videoname>`
- [ ] [Create a new file](https://github.com/blog/1327-creating-files-on-github) labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one! Fill it in with your script for the video challenge.

#### 3. Open a Pull Request
- [ ] Navigate back to the [FreeCodeCamp/hikes repository](https://github.com/freecodecamp/hikes) and  propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a [Pull Request](https://help.github.com/articles/creating-a-pull-request/).
- [ ] In the body of the pull request, `@` mention brianamarie for feedback, like this: @brianamarie. 

#### 4. Record your video
- [ ] Set up a whiteboard and record your video.
- [ ] Upload the video to YouTube. Ideally, the privacy will be set to 'private', so only those with the link can view. 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie. You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com

#### 5. Getting your video on Free Code Camp
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site.
By this point, we will help you complete a few more steps. We're working on adding instructions so you don't have to wait on us! These steps include:
- Uploading your video to the [Free Code Camp YouTube site](https://www.youtube.com/c/freecodecamp).
- Adding an [image overlay to a video thumbnail](https://github.com/FreeCodeCamp/hikes/tree/master/videoThumbnails) to display on YouTube.
- Adding the script, questions, and video link to the [Free Code Camp JSON seed code](https://github.com/FreeCodeCamp/FreeCodeCamp/tree/staging/seed/challenges/04-video-challenges) and opening a Pull Request to get it added. 

----

@SEGrooms I'd <3 to add  you in the step 3 for feedback review if and when you're willing. 😄  Also, if/when you write a blog post, I think it'd be ✨  to add it to the list in step 1 for research. 

@atjonathan 💭 Thoughts?

**Comment by atjonathan** [comment]
> I have a question...will contributors need a certain access to be able to add labels? It was my understanding that users needed collaborator access to be able to do that.
I'd add these myself but can't because it's on your branch - thoughts?

These are only tickboxes, with the current status of the issue. We can add labels ourselves.

Do you want the above contents to be in the issue template?

**Comment by brianamarie** [comment]
> These are only tickboxes, with the current status of the issue. We can add labels ourselves.

Ah, gotcha, thanks. I missed that. :)


> Do you want the above contents to be in the issue template?

Yes - I think it will be a helpful guide for contributors to have a step by step list of what to do. What do you think?

**Comment by atjonathan** [comment]
@brianamarie, this is what will be shown for video requests. They might not want to make the videos, maybe take a different approach?

**Comment by atjonathan** [comment]
@brianamarie, update on this?
Please see https://github.com/FreeCodeCamp/hikes/pull/190#issuecomment-223617520

**Comment by brianamarie** [comment]
@atjonathan Thank you for the ping!  🙇 

If it's just what will be shown for a video request, I think that should be simpler. Maybe a request to check out the existing videos and issues before posting? What do you think?

**Comment by atjonathan** [comment]
@brianamarie, we could add some markdown comments, telling campers to check existing issues so they don't create a duplicate request.

We should also maybe add some form of organization for the request:
```markdown
#### Name of requested series:
<!-- STILL TO ADD -->
#### Proposed episodes for series:
<!-- STILL TO ADD -->
#### Description of content:
<!-- STILL TO ADD -->
#### Current Status:
- [ ] ![01: Help Wanted](https://img.shields.io/badge/Label-01: Help Wanted-000000.svg)
- [ ] ![02: Scripting](https://img.shields.io/badge/Label-02: Scripting-000000.svg)
- [ ] ![03: Recording](https://img.shields.io/badge/Label-03: Recording-000000.svg)
- [ ] ![04: Reviewing](https://img.shields.io/badge/Label-04: Reviewing-000000.svg)
- [ ] ![05: Finalizing](https://img.shields.io/badge/Label-05: Finalizing-000000.svg)
```

**Comment by brianamarie** [comment]
@atjonathan I think that's great - I say go ahead and merge! 🚢

**Comment by atjonathan** [comment]
@brianamarie, merge at will :ship:, remember to `squash` :stuck_out_tongue_winking_eye:

**Comment by brianamarie** [comment]
@atjonathan Fantastic, will do!!! Thank you!

**Pull request merged**
