### PR TITLE
Reorganize README

### LINKED ISSUE #174: Organize README to reflect accurate overview
If anyone is looking for an opportunity to contribute with minimal coding involved, the readme for this repo isn't in great shape.

It would be idea for the readme to reflect the current status of videos in five tiers.
1. Help wanted
2. Pre-production (script has not yet complete, but video has user assigned to start the process)
3. Production (script is complete and has been looked at by other team members, video is not yet complete)
4. Post-production (video has been recorded)
5. Deployed & live

### PR DESCRIPTION
**Pull request by alistermada**
The list turned out to be a lot bigger than I thought. Could possibly split the Proposed Videos list into several tables, one per category, as an alternative.

Also, not sure about the status of the Discrete Mathematics videos. The issues linked are all closed; many without a stated reason.

closes #174
closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7711

### CODE REVIEW

**Comment by theflametrooper** [comment]
Can this be merged @brianamarie ?

**Comment by brianamarie** [comment]
@theflametrooper Thank you for bringing my attention to this, and @alistermada thank you SO MUCH for your great work on this!!! ✨ 😄 ❤️ Please, merge, 🚢 and :shipit: !

**Comment by theflametrooper** [comment]
## LGTM :+1:

Thanks @alistermada, this is a great improvement!

**Comment by theflametrooper** [comment]
@alistermada The problem with this README is that it has to be updated every time we add, update or remove a video.

**Comment by alistermada** [comment]
@theflametrooper Yes, what was requested in #174 was that the README reflect the current status of videos.

Would an alternative suggestion like an app or online document to store the list of videos be better or is it okay for this README to be continuously updated?

**Comment by theflametrooper** [comment]
@alistermada It's very inefficient to keep updating the README. Possibly some form of Google Doc / Something Similar.

**Pull request merged**
