### PR TITLE
Script for What is an Algorithm?

### PR DESCRIPTION
**Pull request by PizzaPokerGuy**
Video: https://www.youtube.com/watch?v=kt7GOXd_n24

### CODE REVIEW

**Comment by atjonathan** [comment]
@PizzaPokerGuy, please add your script to `/video-categories/computer-science` and make a new folder there called **`scripts`**. Inside that folder, make a file called **what-is-an-algorithm.md**.

You also have just got a plain text file in this document. Please try and add formatting using markdown (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

**Comment by PizzaPokerGuy** [comment]
@atjonathan Sounds good. Sent Quincy the video. Going to wait to see what he says before moving forward.

**Comment by brianamarie** [comment]
@PizzaPokerGuy WOW! 😍 This is so fantastic! Right off the bat, I want to say **thank you** for all of the amazing work you've put into this. After looking at some of your other videos, I can tell you have a passion and a knack for helping others learn about tech, which is close to my heart. 😄 ❤️ 

A few pieces of teeny, picky feedback: 

Pros: 
- I love the background and the white board! How did you do this? Even though it's different than other videos we have up right now, I really like it! One question: Is there any way to put _less_ text on the white board there that is repeated verbally? I only ask because I know many users watch these videos from their tablets or phones, and small text might be difficult to read. 

- So many aspects of your video seem _so professional!_ I think a small change that would make a big difference in enhancing the level of production would be best to record it in one take with no cuts, if at all possible. One fluid take adds a sense of continuity. Some of my earlier videos didn't meet this, but if/when I get the chance to re-record, this is one of my goals. 👍 

- You have a great speaking voice! 😄  But, at times it's a bit difficult to hear you. Is there any way you could talk a bit slower and louder in your recording space, or put the microphone a bit closer to you? With my setup, my microphone and camera are one device, so I understand if that's not possible, but I do think any extra clarity in recording and speaking would be good. Your words are so well chosen, I'd hate for anyone to miss any of them. 

- I really like the algorithm example! I appreciate that not only did you talk through the concept of an algorithm, but you showed the steps in a practical way that will make sense to the campers using Free Code Camp. For me, the most difficult thing about learning algorithms was that they seemed so similar to methods. You showing how to use methods within an algorithm made a lot of sense to me. ✨ 

> Please remove the intro and popups saying "like and share". Feel free to introduce yourself at the start of the videos, but please don't link to your own content. The outro about your channel and the freecodecamp shop can also be removed. Once this has been fixed, feel free to add the synced audio recording you talked about 😄

I agree with @atjonathan here. Just as you've done a great job creating a brand for the videos on your own channel, we want to keep as many constants as possible with the videos on Free Code Camp. Maybe a compromise would be to link to your channel in the description...thoughts @QuincyLarson @PizzaPokerGuy @atjonathan?

----

@PizzaPokerGuy As I said before, I think this is all so ✨ and I'm SO glad that Free Code Camp's hike repository and project has caught your eyes. 😄 @PizzaPokerGuy You mentioned that you sent this to @QuincyLarson, which is a great idea. Any and all folks involved in this thread, please feel free to reach out to me here or on Gitter if there's any way I can help or if there is clarity needed on my comments above. ❤️

**Comment by atjonathan** [comment]
@brianamarie, yeh we can stick a link in the description no problem. And yeh, this was a great video @PizzaPokerGuy :smiley:

**Comment by PizzaPokerGuy** [comment]
- The audio will be fixed when I sync up the microphone. It is kind of bad cause I'm using the camera mic in the rough draft.

- What would you like the white board text to say? Also, I can make the whiteboard larger if you prefer? Also only about 12% of your users watch your videos on devices which aren't a computer so I think you might be over thinking it about the text size.

- In regards to recording it in 1 fluid speech it is not going to happen. 

- For the introduction and outro I mentioned to Quincy I would make one for FreeCodeCamp. I just included it for viewing purposes to see if either would work or how he would like it to change.

- Put me in the description if you would like for this video however video descriptions are essentially useless. Moving forward I will not be making additional Hikes unless it is agreed upon for an outro.

Best of luck all. It was fun making this. I'll be removing the intro, remove share/like, remove outro and sync better audio this weekend and re-submit it.

**Comment by PizzaPokerGuy** [comment]
Here is the updated video. I slightly changed the outro to what Quincy told me to change it to. Let me know if it is okay or if any other changes need to be made.
https://youtu.be/QsegJ8_9PBU

**Comment by PizzaPokerGuy** [comment]
@brianamarie @atjonathan Just following up if this video will work or not?

**Comment by atjonathan** [comment]
@PizzaPokerGuy, this videos looks good to me :+1:, sorry for the delay :disappointed: 
cc/ @brianamarie @QuincyLarson

**Comment by atjonathan** [comment]
@PizzaPokerGuy The one thing I noticed was at the start you show a small popup.

[https://gyazo.com/c1649b6adc3f6b7f1be1117a895b8b70](https://gyazo.com/c1649b6adc3f6b7f1be1117a895b8b70)

This is cool, however the logo does not conform to our style guide:
[https://gyazo.com/c7bf3f126e5bc960612dd5c9ada4b697](https://gyazo.com/c7bf3f126e5bc960612dd5c9ada4b697)

You can get any of our assets [here]() :smiley: 

Once you've fixed this, you can send me on gitter a link to the video file directly instead of putting it on youtube. I will then upload it as unlisted on our channel awaiting review from @QuincyLarson and @brianamarie whom I will contact separately :+1: 

Sorry for the wait, Briana is on her honeymoon and the rest of the team is busy with reactifying the site!

**Comment by QuincyLarson** [comment]
@PizzaPokerGuy I haven't heard from you in a while, so I'm closing this issue (housekeeping). If you're interested in contributing videos in the future, you can reopen it. Thanks for making such well produced videos over at Coding Tutorials 360.

**Pull request closed without merging**
