### PR TITLE
Update the README.md 

### PR DESCRIPTION
**Pull request by mrpatil007**
Added waffle graph to see the contribution progress in graphical manner

### CODE REVIEW

**Comment by atjonathan** [comment]
@mrpatil007, was the script not already added?

**Comment by mrpatil007** [comment]
@atjonathan oh ya actually when a make a PR my previous commit appear automatically i rebase it but it appear any suggestion what i need to do to remove the previous commit :smile:

**Comment by atjonathan** [comment]
@mrpatil007 try `git rebase -i HEAD~n` and, on the commit you want to remove, switch `squash1

**Comment by mrpatil007** [comment]
@atjonathan i delete previous commit. Now Review it Let's merge it

**Comment by atjonathan** [comment]
@mrpatil007, you should never merge your own PRs!

**Comment by mrpatil007** [comment]
@atjonathan ok sorry i don't know about that

**Comment by atjonathan** [comment]
@mrpatil007, np!

**Comment by SEGrooms** [comment]
Don't worry @mrpatil007, @atjonathan got me on that too! ;)

**Pull request merged**
