### PR TITLE
Start machine learning section

### LINKED ISSUE #108: What is Machine Learning?

### PR DESCRIPTION
**Pull request by erictleung**
Closes #108.

I'd be interested in helping out with the machine learning section of the hikes. Currently taking a course on machine learning. It'll be important for what I do in school so it'll be good review for me to work out the scripts and possibly videos as well.

Let me know if there's any issues with file names of the hikes list I've created.

### CODE REVIEW

**Comment by brianamarie** [comment]
@erictleung This is fantastic - I apologize for the long wait time on your end.

Are you still interested in contributing further? Specifically, would you be interested in creating a video with this ✨  **great** ✨  script you've written on machine learning?

**Comment by erictleung** [comment]
@brianamarie no worries on the wait. And thanks! Although I'm hesitant to make videos because of my camera shyness, I'd still like to contribute and make a video! :blush:

Some questions for you (sorry for so many!). How do you usually coordinate the development of new hikes, through PMs or through the hikes room? And Is there a specific timeline you'd like to reach for on creating the videos? I'm guessing I can look at the already made videos on guidelines on how to format my videos as well? Or do you have a document on how you'd like them to look?

**Comment by brianamarie** [comment]
> I'd still like to contribute and make a video!

@erictleung 🎉 🎈 🍕 😄 



> How do you usually coordinate the development of new hikes, through PMs or through the hikes room?

We have yet to streamline this process. Currently, there's no official process, but I'd like that to change in the future. 

**I really love what you've done here by creating a PR with the script!** How does this look to you? 
----
- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [x] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Get in touch with `@Rybar` about [adding banners to thumbnails for videos](https://github.com/FreeCodeCamp/hikes/pull/158)
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site
----

> And Is there a specific timeline you'd like to reach for on creating the videos?

Traffic on our channel is growing, and we'd love your videos up as soon as possible!  That being said, there is no deadline on this. I'm so thrilled that you're interested in contributing, and I want to be respectful of your other responsibilities. As with all community open source projects, if you later realize that you aren't able to work on it, let us know so we can re-add 'help wanted'. 

> I'm guessing I can look at the already made videos on guidelines on how to format my videos as well? Or do you have a document on how you'd like them to look? 

Basic guidelines are in the links above, but some short points include:
- Use a whiteboard/blackboard with the title of the video and main points 
- Try to make sure lighting, audio, etc., is professional as possible for your situation
- Video length should be between 1-3 minutes
- Remember your audience: say things as simply as possible, and always tell them how, when, and why they'll use this information 

@erictleung As I said, I'm so thrilled you're interested in this! Please let me know if there's anything I can do to help you along the way with this. 😸 💯 💚

**Comment by brianamarie** [comment]
cc/ @QuincyLarson

**Comment by atjonathan** [comment]
@erictleung closing as stale.. Please reopen when you have worked on some more of this section :smiley:

**Pull request closed without merging**
